import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import 'fig-css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { GoogleAnalytics } from '@next/third-parties/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
      <GoogleAnalytics gaId="G-7SHR06DB9Q" />
    </html>
  );
}
